### ISSUE TITLE
Closing paragraph tag where none is open

### ISSUE THREAD

**Issue by crusy** [wolfgang101/include-mastodon-feed#6]
See [blog.crusy.net](https://validator.w3.org/nu/?doc=https%3A%2F%2Fblog.crusy.net%2F):
`No p element in scope but a p end tag seen.`

I traced this down to the third (out of three) `return ob_get_clean();` in [line 748](https://github.com/wolfgang101/include-mastodon-feed/blob/4f6fa6aa5536b209aa13f707a52d5b43126e9459/plugin.php#L748): when I return "" instead, the DOM contains a valid (though still unnecessary) `<p></p>`, but in the current state of returning `ob_get_clean()` only `<p/>` is printed – leading to an invalid DOM.

Now as `ob_get_clean()` is [a built-in function of php](https://www.php.net/manual/en/function.ob-get-clean.php) I guess this might be a bug of PHP (though I'm not an expert here, obviously). So I double checked with at least 8.1 and 8.3, but the problem persists. And as a) `ob_start()` and `ob_get_clean()` is used intentionally, and b) I cannot spot any difference when returning the empty String instead anyways, I thought this is at least _also_ a problem of this plugin ...

**Comment by wolfgang101** [comment]
Notes after a joint debugging session for other users:

We tested the Custom HTML and Shortcode block inside a sidebar widget. The Custom HTML block produced clean output, but the shortcode block added <p> tags.

After further research this seems to be a known issue since 17 years https://core.trac.wordpress.org/ticket/6984

There are even plugins that try to mitigate the issue, but an easy workaround that seems to work fine right now is to just wrap the shortcode inside a <div>.

This worked inside a shortcode block inside a sidebar widget:

`<div>[include-mastodon-feed instance="chaos.social" account="111784504453496359"]</div>`

Source: https://wordpress.org/support/topic/invalid-paragraph-tag/
